/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pharmondev_computercontrol_crc32_JNICRCImpl */

#ifndef _Included_com_pharmondev_computercontrol_crc32_JNICRCImpl
#define _Included_com_pharmondev_computercontrol_crc32_JNICRCImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pharmondev_computercontrol_crc32_JNICRCImpl
 * Method:    pabb_crc32_SSE42
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_com_pharmondev_computercontrol_crc32_JNICRCImpl_pabb_1crc32_1SSE42
  (JNIEnv *, jclass, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
